# Generated by Django 5.1.4 on 2024-12-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectCore', '0004_alter_board_name_alter_task_board_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
